name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: put weather in github env
        run: cat result.html | xargs -I {} bash -c 'echo "DAILY_WEATHER={}" >> $GITHUB_ENV'
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Chennai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: Send telegram email message to telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          document: result.html
          message: |
                   Chennai Weather Report (${{env.REPORT_DATE}})
                   (${{env.DAILY_WEATHER}})
